services:
  - type: web
    name: n8n
    env: node
    plan: starter
    buildCommand: |
      bash -lc '
      set -e
      corepack enable
      corepack prepare pnpm@8.15.6 --activate
      pnpm -w install --frozen-lockfile
      # Compila SOLO el CLI y sus dependencias (evita frontends)
      pnpm -w -r --filter @n8n/cli... build
      '
    # Exporta N8N_PORT desde el PORT que Render asigna en runtime
    startCommand: |
      bash -lc '
      export N8N_PORT=$PORT
      cd packages/cli
      node ./bin/n8n
      '
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: TZ
        value: America/Bogota
      - key: N8N_DIAGNOSTICS_ENABLED
        value: "false"
